{{- if and .Values.knownHosts (not .Values.existingKnownHostsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-ssh" (include "jconfig.fullname" .) }}
  labels:
    {{- include "jconfig.labels" . | nindent 4 }}
type: Opaque
stringData:
  known_hosts: |
{{ .Values.knownHosts | indent 4 }}
{{- end }}
